[package]
name = "ray_tracing"
version = "0.1.0"
authors = ["Victor Cornillere <v.cornillere@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
rand = "0.6.5"
ncollide3d = "0.19.1"
nalgebra = "0.18.0"
rayon = "1.0.3"
obj = "0.9.0"
num-traits = "0.2.8"
